-- 1. Create the 'device_states' table
CREATE TABLE IF NOT EXISTS device_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device TEXT NOT NULL,
    state TEXT NOT NULL,
    user_email TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE device_states ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to insert logs (for demo purposes)
-- In a production app, you would restrict this to authenticated users only.
CREATE POLICY "Allow anonymous inserts" 
ON device_states 
FOR INSERT 
WITH CHECK (true);

-- 4. Create a policy to allow users to read all logs
CREATE POLICY "Allow public read access" 
ON device_states 
FOR SELECT 
USING (true);

-- 5. Optional: Add an index on created_at for faster history retrieval
CREATE INDEX IF NOT EXISTS idx_device_states_created_at ON device_states (created_at DESC);
