-- 1. Create the device_states table with full context
CREATE TABLE IF NOT EXISTS public.device_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device TEXT NOT NULL,                  -- "Light" or "Fan"
    state TEXT NOT NULL,                   -- "ON" or "OFF"
    user_email TEXT DEFAULT 'anonymous',   -- For easy viewing in the demo
    timestamp TEXT,                        -- ISO string from the app
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Performance Indexing
-- Optimize for fetching the latest 10 logs (used in your dashboard)
CREATE INDEX IF NOT EXISTS idx_device_states_created_at ON public.device_states (created_at DESC);

-- 3. Security Configuration
-- Disable RLS for the demo to ensure your common "anon" key works immediately
ALTER TABLE public.device_states DISABLE ROW LEVEL SECURITY;

-- 4. Enable Realtime Triggers
-- This allows the UI to update instantly if a third-party app changes the state
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' 
    AND schemaname = 'public' 
    AND tablename = 'device_states'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.device_states;
  END IF;
END $$;

-- 5. Add helpful table comments
COMMENT ON TABLE public.device_states IS 'Logs of all smart home appliance state changes triggered by gestures.';
