-- 1. Create the device_states table
CREATE TABLE IF NOT EXISTS public.device_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device TEXT NOT NULL,
    state TEXT NOT NULL,
    timestamp TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Allow public access to insert and read device_states easily
-- (Disable RLS for simplicity during development since this relies on anon key)
ALTER TABLE public.device_states DISABLE ROW LEVEL SECURITY;

-- 3. Enable Realtime triggers so the frontend can listen to changes (optional, but good practice)
ALTER PUBLICATION supabase_realtime ADD TABLE public.device_states;
